-- MySQL Script generated by MySQL Workbench
-- Mon 02 Oct 2017 04:56:46 PM CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PaintbrushLocal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PaintbrushLocal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PaintbrushLocal` DEFAULT CHARACTER SET utf8 ;
USE `PaintbrushLocal` ;

-- -----------------------------------------------------
-- Table `PaintbrushLocal`.`EstablishedUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PaintbrushLocal`.`EstablishedUsers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL,
  `MiddleName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `LocalID` VARCHAR(45) NULL,
  `PrivateEmail` VARCHAR(45) NULL,
  `InstitutionEmail` VARCHAR(45) NULL,
  `HomePhone` INT NULL,
  `CellPhone` INT NULL,
  `InstitutionLookupCode` VARCHAR(255) NULL,
  `Address` VARCHAR(45) NULL,
  `Birthday` DATE NULL,
  `AccentColor` VARCHAR(45) NULL,
  `Schedule` VARCHAR(255) NULL,
  `LoadByDefault` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PaintbrushLocal`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PaintbrushLocal`.`table1` (
)
ENGINE = InnoDB;

USE `PaintbrushLocal` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `PaintbrushLocal`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
